name: Build & tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: |
        sudo apt-key add A9897320C397E3A60C03E8BF821AD320F71BFF3D &&
        sudo echo "deb https://packagecloud.io/varnishcache/varnish64/ubuntu/ bionic main" > /etc/apt/sources.list.d/varnish.list &&
        sudo apt-get update &&
        sudo apt-get install -y varnish-dev
    - name: autogen
      run: autogen    
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
